### ISSUE TITLE
Error Module Not Found : Socks

### ISSUE THREAD

**Issue by akgupta0777** [rahnumaa18/https-github.com-avramit-Instahack#1]
I am attaching screenshot of the error in hackinsta.py
![Screenshot_2019-08-24-10-48-52-994_com termux](https://user-images.githubusercontent.com/51379307/63632893-f9b21800-c65c-11e9-97f0-bb7a9edd7aff.png)

**Comment by HosseyNJF** [comment]
Just run this:
`pip install pysocks`

**Comment by akgupta0777** [comment]
after installing pysocks it gaves module error pybroker not found

**Comment by K03N** [comment]
Same ^
